# Generated by Django 4.2 on 2023-04-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('work_experience', models.CharField(max_length=30, verbose_name='Work experience since some year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.employee')),
                ('inn', models.IntegerField(max_length=14, verbose_name='INN PASSPORT')),
                ('id_card', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Number_id_passport')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.employee',),
        ),
        migrations.CreateModel(
            name='VIPClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.client')),
                ('vip_status_start', models.DateField()),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vip_clients',
            },
            bases=('app.client',),
        ),
        migrations.CreateModel(
            name='WorkProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(related_name='groups', through='app.Membership', to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='work_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workprojects'),
        ),
    ]
